# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - dev
    exclude:
      - master
  paths:
    exclude:
      - azure-pipelines.yml

pool:
  vmImage: 'macOS-latest'

steps:

# - script: echo Setup for XamariniOS Build
#   displayName: 'Run a one-line script'

  # - task: NuGetToolInstaller@1
  #   displayName: 'Install NuGet 4.5'
  #   inputs:
  #     versionSpec: '4.5'

  # - task: NuGetCommand@2
  #   displayName: 'Restore NuGet - iOS proj'
  #   inputs:
  #     command: 'restore'
  #     restoreSolution: '**/*ios.csproj'
  #     feedsToUse: 'select'

  - task: XamariniOS@2
    displayName: 'Build iOS proj'
    inputs:
      solutionFile: '**/*.sln'
      configuration: 'Debug'
      packageApp: false
      buildForSimulator: true
      runNugetRestore: false


# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
